runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: production
  VITE_GEMINI_API_KEY: ""
  GE_KEY: ""

handlers:
  - url: /assets
    static_dir: dist/assets
  - url: /.*
    script: auto
