runtime: nodejs24
instance_class: F1

env_variables:
  NODE_ENV: production
  GE_KEY: "your_actual_key"   # backend only

handlers:
  - url: /assets
    static_dir: dist/assets
    http_headers:
      Cache-Control: "no-cache"

  - url: /.*
    script: auto
    http_headers:
      Cache-Control: "no-cache"